AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvName:
    Type: String
    Default: dev
Conditions:
  IsProd:
    !Equals [!Ref EnvName, "prod"]
Resources:
  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api
      EndpointConfiguration:
        Types:
          - REGIONAL
  BattlesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref API
      ParentId: !GetAtt API.RootResourceId
      PathPart: battles
  BattlesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref BattlesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !ImportValue BattlesGetLambdaArn]
        PassthroughBehavior: NEVER
  BattlesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref BattlesResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !ImportValue BattlesPostLambdaArn]
        PassthroughBehavior: NEVER
  VotesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref API
      ParentId: !GetAtt API.RootResourceId
      PathPart: votes
  VotesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref VotesResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !ImportValue VotesPostLambdaArn]
        PassthroughBehavior: NEVER
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If [IsProd, "api.bitterbattles.com", !Sub "api-${EnvName}.bitterbattles.com"]
      ValidationMethod: DNS
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties: 
      DomainName: !If [IsProd, "api.bitterbattles.com", !Sub "api-${EnvName}.bitterbattles.com"]
      RegionalCertificateArn: !Ref Certificate
      EndpointConfiguration:
        Types:
          - REGIONAL
  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: BattlesGetMethod
    Properties:
      RestApiId: !Ref API
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref API
      DeploymentId: !Ref Deployment
      StageName: !Ref EnvName
  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref API
      Stage: !Ref Stage