AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvName:
    Type: String
    Default: dev
  BattlesTableRCUs:
    Type: Number
    Default: 1
  BattlesTableWCUs:
    Type: Number
    Default: 1
  BattlesTableUserIdRCUs:
    Type: Number
    Default: 1
  BattlesTableUserIdWCUs:
    Type: Number
    Default: 1
  VotesTableRCUs:
    Type: Number
    Default: 1
  VotesTableWCUs:
    Type: Number
    Default: 1
  RedisNodeType:
    Type: String
    Default: cache.t2.micro
Conditions:
  IsProd:
    !Equals [!Ref EnvName, "prod"]
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  Subnet0:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: 10.0.0.0/18
      MapPublicIpOnLaunch: false
  Subnet0RouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet0
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: 10.0.64.0/18
      MapPublicIpOnLaunch: false
  Subnet1RouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet1
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs ""]
      CidrBlock: 10.0.128.0/18
      MapPublicIpOnLaunch: false
  Subnet2RouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet2
  DynamoEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !Ref VPC
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      RouteTableIds:
        - !Ref RouteTable
  BattlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: battles
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref BattlesTableRCUs
        WriteCapacityUnits: !Ref BattlesTableWCUs
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref BattlesTableUserIdRCUs
            WriteCapacityUnits: !Ref BattlesTableUserIdWCUs
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  VotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: votes
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref VotesTableRCUs
        WriteCapacityUnits: !Ref VotesTableWCUs
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: battleId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: battleId
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: A group of subnets for redis.
      SubnetIds:
        - !Ref Subnet0
        - !Ref Subnet1
        - !Ref Subnet2
  Redis:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: Multi-AZ redis cluster.
      Engine: redis
      CacheNodeType: !Ref RedisNodeType
      AutomaticFailoverEnabled: true
      NumCacheClusters: 3
      PreferredCacheClusterAZs:
        - !Select [0, !GetAZs ""]
        - !Select [1, !GetAZs ""]
        - !Select [2, !GetAZs ""]
      CacheSubnetGroupName: !Ref SubnetGroup
      SecurityGroupIds:
        - !GetAtt VPC.DefaultSecurityGroup
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ServiceRoleForLambda
      Path: /service-role/
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - dynamodb:ListStreams
                  - dynamodb:DescribeStream
                  - dynamodb:GetShardIterator
                  - dynamodb:GetRecords
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - ec2:DescribeNetworkInterfaces
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                Resource: "*"
  BattlesGetLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: battles-get
      Code:
        S3Bucket: !If [IsProd, "bitterbattles-api-lambda", !Sub "bitterbattles-api-${EnvName}-lambda"]
        S3Key: battles-get.zip
      Runtime: go1.x
      Handler: battles-get
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
      Environment:
        Variables:
          REDIS_ADDRESS: !Join ["", [!GetAtt Redis.PrimaryEndPoint.Address, ":", !GetAtt Redis.PrimaryEndPoint.Port]]
  BattlesPostLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: battles-post
      Code:
        S3Bucket: !If [IsProd, "bitterbattles-api-lambda", !Sub "bitterbattles-api-${EnvName}-lambda"]
        S3Key: battles-post.zip
      Runtime: go1.x
      Handler: battles-post
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
  BattlesDeleteLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: battles-delete
      Code:
        S3Bucket: !If [IsProd, "bitterbattles-api-lambda", !Sub "bitterbattles-api-${EnvName}-lambda"]
        S3Key: battles-delete.zip
      Runtime: go1.x
      Handler: battles-delete
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
  BattlesStreamLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: battles-stream
      Code:
        S3Bucket: !If [IsProd, "bitterbattles-api-lambda", !Sub "bitterbattles-api-${EnvName}-lambda"]
        S3Key: battles-stream.zip
      Runtime: go1.x
      Handler: battles-stream
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
      Environment:
        Variables:
          REDIS_ADDRESS: !Join ["", [!GetAtt Redis.PrimaryEndPoint.Address, ":", !GetAtt Redis.PrimaryEndPoint.Port]]
  VotesPostLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: votes-post
      Code:
        S3Bucket: !If [IsProd, "bitterbattles-api-lambda", !Sub "bitterbattles-api-${EnvName}-lambda"]
        S3Key: votes-post.zip
      Runtime: go1.x
      Handler: votes-post
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
  VotesStreamLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: votes-stream
      Code:
        S3Bucket: !If [IsProd, "bitterbattles-api-lambda", !Sub "bitterbattles-api-${EnvName}-lambda"]
        S3Key: votes-stream.zip
      Runtime: go1.x
      Handler: votes-stream
      Role: !GetAtt LambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !Ref Subnet0
          - !Ref Subnet1
          - !Ref Subnet2
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
  BattlesStreamTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt BattlesTable.StreamArn
      FunctionName: !GetAtt BattlesStreamLambda.Arn
      Enabled: true
      BatchSize: 100
      StartingPosition: TRIM_HORIZON
  VotesStreamTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt VotesTable.StreamArn
      FunctionName: !GetAtt VotesStreamLambda.Arn
      Enabled: true
      BatchSize: 100
      StartingPosition: TRIM_HORIZON
  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: api
      EndpointConfiguration:
        Types:
          - REGIONAL
  BattlesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref API
      ParentId: !GetAtt API.RootResourceId
      PathPart: battles
  BattlesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref BattlesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !GetAtt BattlesGetLambda.Arn]
        PassthroughBehavior: NEVER
  BattlesGetPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt BattlesGetLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub ["arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API}/*/GET/battles", API: !Ref API]
  BattlesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref BattlesResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !GetAtt BattlesPostLambda.Arn]
        PassthroughBehavior: NEVER
  BattlesPostPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt BattlesPostLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub ["arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API}/*/POST/battles", API: !Ref API]
  BattlesDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref BattlesResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !GetAtt BattlesDeleteLambda.Arn]
        PassthroughBehavior: NEVER
  BattlesDeletePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt BattlesDeleteLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub ["arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API}/*/DELETE/battles", API: !Ref API]
  VotesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref API
      ParentId: !GetAtt API.RootResourceId
      PathPart: votes
  VotesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref API
      ResourceId: !Ref VotesResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub ["arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations", LambdaArn: !GetAtt VotesPostLambda.Arn]
        PassthroughBehavior: NEVER
  VotesPostPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt VotesPostLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub ["arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API}/*/POST/votes", API: !Ref API]
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If [IsProd, "api.bitterbattles.com", !Sub "api-${EnvName}.bitterbattles.com"]
      ValidationMethod: DNS
  DomainName:
    Type: AWS::ApiGateway::DomainName
    Properties: 
      DomainName: !If [IsProd, "api.bitterbattles.com", !Sub "api-${EnvName}.bitterbattles.com"]
      RegionalCertificateArn: !Ref Certificate
      EndpointConfiguration:
        Types:
          - REGIONAL
  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: BattlesGetMethod
    Properties:
      RestApiId: !Ref API
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref API
      DeploymentId: !Ref Deployment
      StageName: !Ref EnvName
  BasePath:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref API
      Stage: !Ref Stage
      BasePath: "v1"